name: Fetch and Normalize Cloud Instance Data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0' # Weekly (disabled for manual testing)

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased timeout for browser automation
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Fetch AWS data
      #   run: python scripts/fetch_aws.py

      # - name: Fetch Azure data
      #   run: python scripts/fetch_azure.py

      # - name: Fetch OCI data
      #   run: python scripts/fetch_oci.py

      # - name: Fetch Google data
      #   run: python scripts/fetch_google.py

      - name: Fetch Hetzner data
        run: python scripts/fetch_hetzner.py
        env:
          # Hetzner Cloud API credentials (Robot API disabled for now)
          HETZNER_API_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}
        timeout-minutes: 3

      # - name: Fetch OVH data
      #   run: python scripts/fetch_ovh.py
      
      - name: Commit and push data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update cloud instance data [skip ci]"
          file_pattern: data/*.json
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          push_options: '--force-with-lease'